# railway.yaml
# Defines the services, build steps, and deployment configuration for Railway.

$schema: https://railway.app/railway.schema.json

services:
  # --- Your Node.js Web Application ---
  - name: web
    build:
      # Use nixpacks, Railway's default buildpack, which auto-detects Node.js
      builder: nixpacks
      # Explicitly define the build command (runs after dependencies are installed)
      buildCommand: npm install
      # --- Add Nixpacks config to be explicit ---
      # This tells the builder (Nixpacks) what start command to use
      # This is an extra layer of configuration to ensure the correct
      # start command is baked into the build image.
      nixpacksConfig:
        start:
          cmd: node server.js
    deploy:
      # The command to run to start your application
      # This *should* override any other detected start command.
      startCommand: node server.js
      # Use the health check endpoint you defined in server.js
      healthcheckPath: /
      # Give the service up to 2 minutes to respond to the health check
      healthcheckTimeout: 120
      # Restart the app if it fails the health check
      restartPolicyType: ON_FAILURE

  # --- Your PostgreSQL Database ---
  - name: postgres
    image: postgres:15
    # Railway will automatically link this service and provide the DB_URI
    # to your 'web' service.
