# railway.yaml
# Defines the services, build steps, and deployment configuration for Railway.

$schema: https://railway.app/railway.schema.json

services:
  # --- Your Node.js Web Application ---
  - name: web
    build:
      # Use nixpacks, Railway's default buildpack
      builder: nixpacks
      # Build from the server directory
      buildCommand: cd server && npm install
    deploy:
      # CORRECTED: The actual path to your server file
      startCommand: cd server && node src/server.js
      # Use the health check endpoint
      healthcheckPath: /
      # Give the service time to start up
      healthcheckTimeout: 300
      # Restart the app if it fails
      restartPolicyType: ON_FAILURE
    # Define environment variables needed
    envVars:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "3000"

  # --- Your PostgreSQL Database ---
  - name: postgres
    image: postgres:15
    # Railway will automatically link this service and provide the DATABASE_URL